# Generated by Django 3.1.2 on 2020-10-17 03:15

import app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201017_1006'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.managers.UserManager()),
            ],
        ),
    ]
