# Generated by Django 3.1.2 on 2020-10-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201017_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=128),
        ),
    ]
