# Generated by Django 3.1.2 on 2020-10-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='gender',
        ),
    ]
