# Generated by Django 3.1.2 on 2020-10-17 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201017_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(default=datetime.date(2020, 10, 17), verbose_name='date of birth'),
        ),
    ]
