# Generated by Django 3.1.2 on 2020-10-17 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201017_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
    ]
