# Generated by Django 3.1.2 on 2020-10-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201017_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(auto_now_add=True, verbose_name='birthdate'),
        ),
    ]
